### ISSUE TITLE
Where is the make_parallel_enc_dec funciton?

### ISSUE THREAD

**Issue by wrz1999** [asteroid-team/asteroid-filterbanks#19]
Hello! Where is the make_parallel_enc_dec funciton? Is it deleted?

**Comment by mpariente** [comment]
It's in asteroid-filterbanks : https://github.com/asteroid-team/asteroid-filterbanks

**Comment by wrz1999** [comment]
Which file has it? How to call the function? Thank you.

**Comment by mpariente** [comment]
https://github.com/asteroid-team/asteroid-filterbanks/blob/master/asteroid_filterbanks/__init__.py#L14

**Comment by wrz1999** [comment]
I saw the "make_parallel_enc_dec" function in a project. This function needs to input the number of channels to turn multi-channel audio into two-dimensional features. Is there any difference between this one and the current one? What's meaning of the "parallel"? The "make_parallel_enc_dec" function appears in this project:
https://github.com/hangtingchen/Beam-Guided-TasNet/blob/main/model.py

**Comment by mpariente** [comment]
It does not exist in Asteroid. You should open an issue in the repo you linked to.
